# Generated by Django 2.0.3 on 2019-02-05 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20190205_0941'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='type_of_pizza',
        ),
    ]
