# Generated by Django 2.0.3 on 2019-02-05 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20190205_1255'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='type_of_pizza',
            new_name='Category',
        ),
    ]
